In [1]:
import sqlite3
import pandas as pd
con=sqlite3.connect('C:\\Users\\yasee\\OneDrive\\Desktop\\Sem 3 projects\\project 3.1\\data\\raw\\ipl.db')

def q(sql):
    return pd.read_sql(sql,con)

In [2]:
def run_sql_file(path):
    with open(path,'r') as f:
        script=f.read()
        con.executescript(script)
        con.commit()
        print('ran',path)

In [3]:
import ast
import pandas as pd
d = pd.read_sql('SELECT * FROM deliveries WHERE fielders_involved IS NOT NULL ', con )
d['fielders']=d['fielders_involved'].apply(ast.literal_eval)

d=d.explode('fielders')
d['fielders'].value_counts().head(5)

fielders
MS Dhoni          258
KD Karthik        228
RV Uthappa        169
AB de Villiers    148
V Kohli           142
Name: count, dtype: int64

In [4]:
q("""SELECT result,COUNt(*) AS n
FROM matches 
GROUP BY result;""")

      result     n
0  no result     9
1        tie    16
2        win  1187

In [5]:
q("""
-- what is the strike rate of every batter in the death overs

SELECT
    batter,
    ROUND(
         100*SUM(batter_runs) /SUM(
             case
                 WHEN is_wide_ball=0 AND is_no_ball=0
                 THEN 1
                 ELSE 0
             END 
             ),2 
         ) AS strike_rate

FROM deliveries
WHERE over_number BETWEEN 15 AND 19
  AND is_super_over=0
GROUP BY batter
ORDER BY strike_rate DESC ;""")

             batter  strike_rate
0          WG Jacks        483.0
1          DT Patil        400.0
2        KT Maphaka        400.0
3            L Wood        300.0
4          PA Reddy        300.0
..              ...          ...
637     Sunny Gupta          0.0
638          U Kaul          0.0
639  V Pratap Singh          0.0
640   Y Prithvi Raj          0.0
641      YA Abdulla          0.0

[642 rows x 2 columns]

In [6]:
run_sql_file(r'C:\Users\yasee\OneDrive\Desktop\Sem 3 projects\project 3.1\sql\09_analysis_views.sql')

ran C:\Users\yasee\OneDrive\Desktop\Sem 3 projects\project 3.1\sql\09_analysis_views.sql

In [7]:
q("""SELECT * FROM v_ball;""")

,season_id,match_id,batter,bowler,non_striker,over_number,ball_number,batter_runs,extras,total_runs,...,is_super_over,innings,batting_team_id,bowling_team_id,batting_team,bowling_team,phase,is_legal,bowler_runs,bowler_wicket
0,2008,335982,SC Ganguly,P Kumar,BB McCullum,0,0,0,1,1,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
1,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,1,0,0,0,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
2,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,2,0,1,1,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,0,1,0
3,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,3,0,0,0,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
4,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,4,0,0,0,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
288046,2026,1529286,T Stubbs,JC Archer,Ashutosh Sharma,18,3,1,0,1,...,0,2,252,134,Delhi Capitals,Rajasthan Royals,Death,1,1,0
288047,2026,1529286,Ashutosh Sharma,JC Archer,T Stubbs,18,4,1,0,1,...,0,2,252,134,Delhi Capitals,Rajasthan Royals,Death,1,1,0
288048,2026,1529286,T Stubbs,JC Archer,Ashutosh Sharma,18,5,4,0,4,...,0,2,252,134,Delhi Capitals,Rajasthan Royals,Death,1,4,0
288049,2026,1529286,Ashutosh Sharma,Brijesh Sharma,T Stubbs,19,0,4,0,4,...,0,2,252,134,Delhi Capitals,Rajasthan Royals,Death,1,4,0
288050,2026,1529286,Ashutosh Sharma,Brijesh Sharma,T Stubbs,19,1,0,1,1,...,0,2,252,134,Delhi Capitals,Rajasthan Royals,Death,0,1,0

In [8]:
q("""SELECT phase,count(*) FROM v_ball GROUP BY phase;""")

       phase  count(*)
0      Death     65488
1     Middle    132173
2  Powerplay     90390

In [9]:
run_sql_file(r'C:\Users\yasee\OneDrive\Desktop\Sem 3 projects\project 3.1\sql\09_analysis_views.sql')

ran C:\Users\yasee\OneDrive\Desktop\Sem 3 projects\project 3.1\sql\09_analysis_views.sql

In [10]:
run_sql_file(r'C:\Users\yasee\OneDrive\Desktop\Sem 3 projects\project 3.1\sql\09_analysis_views.sql')

ran C:\Users\yasee\OneDrive\Desktop\Sem 3 projects\project 3.1\sql\09_analysis_views.sql

In [11]:
q("""SELECT * from v_match_totals;""")

,match_id,venue_clean,city_clean,season_year,result,match_winner,player_of_match,toss_winner,toss_decision,first_innings_runs,bat_first_team,chase_won
0,335982,M Chinnaswamy Stadium,Bangalore,2008,win,Kolkata Knight Riders,BB McCullum,Royal Challengers Bangalore,field,222,Kolkata Knight Riders,0
1,1082591,Rajiv Gandhi International Stadium,Hyderabad,2017,win,Sunrisers Hyderabad,Yuvraj Singh,Royal Challengers Bangalore,field,207,Sunrisers Hyderabad,0
2,1082592,Maharashtra Cricket Association Stadium,Pune,2017,win,Rising Pune Supergiant,SPD Smith,Rising Pune Supergiant,field,184,Mumbai Indians,1
3,1082593,Saurashtra Cricket Association Stadium,Rajkot,2017,win,Kolkata Knight Riders,CA Lynn,Kolkata Knight Riders,field,183,Gujarat Lions,1
4,1082594,Holkar Cricket Stadium,Indore,2017,win,Punjab Kings,GJ Maxwell,Punjab Kings,field,163,Rising Pune Supergiant,1
...,...,...,...,...,...,...,...,...,...,...,...,...
1182,1529282,Arun Jaitley Stadium,Delhi,2026,win,Royal Challengers Bangalore,JR Hazlewood,Royal Challengers Bangalore,field,75,Delhi Capitals,1
1183,1529283,Maharaja Yadavindra Singh International Cricke...,New Chandigarh,2026,win,Rajasthan Royals,D Ferreira,Rajasthan Royals,field,222,Punjab Kings,1
1184,1529284,Wankhede Stadium,Mumbai,2026,win,Sunrisers Hyderabad,H Klaasen,Mumbai Indians,bat,243,Mumbai Indians,1
1185,1529285,Narendra Modi Stadium,Ahmedabad,2026,win,Gujarat Titans,JO Holder,Gujarat Titans,field,155,Royal Challengers Bangalore,1
1186,1529286,Sawai Mansingh Stadium,Jaipur,2026,win,Delhi Capitals,KL Rahul,Rajasthan Royals,bat,225,Rajasthan Royals,1

In [12]:
q("""SELECT COUNT (*) FROM v_match_totals;""")

   COUNT (*)
0       1187

In [13]:
q("""SELECT COUNT (*) FROm v_innings;""")

   COUNT (*)
0       2418

In [14]:
q("""SELECT phase,COUNT(*) FROM v_ball;""")

       phase  COUNT(*)
0  Powerplay    288051

In [15]:
q(""" 

--Give the list of Highest Runs Scored in IPL History 
--max 5 
SELECT batter,SUM(batter_runs) AS Toatal_runs
FROM v_ball
GROUP bY batter
ORDER BY total_runs DESC
LIMIT 5;""")

                    batter  Toatal_runs
0              A Choudhary           25
1  JPR Scantlebury-Searles            8
2                KK Cooper          116
3             M Theekshana           17
4                RJ Quiney          103

In [16]:
q("""


--list of Highest Six Scored in IPL History

SELECT batter,
       SUM(case when batter_runs=6
             THEN 1
             ELSE 0
             END)AS Total_sixes
FROM v_ball
GROUP BY batter
ORDER BY total_sixes DESC
LIMIT 10;

""")

           batter  Total_sixes
0        CH Gayle          357
1       RG Sharma          311
2         V Kohli          307
3        MS Dhoni          264
4  AB de Villiers          251
5       DA Warner          236
6       SV Samson          234
7        KL Rahul          232
8      AD Russell          223
9      KA Pollard          223

In [17]:
q(""" SELECT * from v_ball""")

,season_id,match_id,batter,bowler,non_striker,over_number,ball_number,batter_runs,extras,total_runs,...,is_super_over,innings,batting_team_id,bowling_team_id,batting_team,bowling_team,phase,is_legal,bowler_runs,bowler_wicket
0,2008,335982,SC Ganguly,P Kumar,BB McCullum,0,0,0,1,1,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
1,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,1,0,0,0,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
2,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,2,0,1,1,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,0,1,0
3,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,3,0,0,0,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
4,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,4,0,0,0,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
288046,2026,1529286,T Stubbs,JC Archer,Ashutosh Sharma,18,3,1,0,1,...,0,2,252,134,Delhi Capitals,Rajasthan Royals,Death,1,1,0
288047,2026,1529286,Ashutosh Sharma,JC Archer,T Stubbs,18,4,1,0,1,...,0,2,252,134,Delhi Capitals,Rajasthan Royals,Death,1,1,0
288048,2026,1529286,T Stubbs,JC Archer,Ashutosh Sharma,18,5,4,0,4,...,0,2,252,134,Delhi Capitals,Rajasthan Royals,Death,1,4,0
288049,2026,1529286,Ashutosh Sharma,Brijesh Sharma,T Stubbs,19,0,4,0,4,...,0,2,252,134,Delhi Capitals,Rajasthan Royals,Death,1,4,0
288050,2026,1529286,Ashutosh Sharma,Brijesh Sharma,T Stubbs,19,1,0,1,1,...,0,2,252,134,Delhi Capitals,Rajasthan Royals,Death,0,1,0

In [18]:
q(""" 
--Higest ball faced by a player,total runs,strike rate

SELECT batter,
            SUM(is_legal)  AS balls,
            SUM(batter_runs)AS runs,
            ROUND(100.0 * SUM (batter_runs)/SUM(is_legal),2) AS strike_rate

 FROM v_ball
 GROUP BY batter
 ORDER BY BALLS DESC
 LIMIT 10;
 """)

       batter  balls  runs  strike_rate
0     V Kohli   6730  9040       134.32
1   RG Sharma   5396  7183       133.12
2    S Dhawan   5302  6769       127.67
3   DA Warner   4675  6565       140.43
4   AM Rahane   4141  5194       125.43
5    KL Rahul   4059  5655       139.32
6    SK Raina   4022  5528       137.44
7    MS Dhoni   3935  5439       138.22
8  RV Uthappa   3782  4952       130.94
9  KD Karthik   3567  4842       135.74

In [19]:
q("""
--Batter who second the highest share of runs in Boundary
SELECT batter,
             SUM(batter_runs)AS  runs,
             ROUND(100.0 *( CASE WHEN batter_runs IN(4,6)
                            THEN batter_runs
                            ELSE 0
                            END)/SUM(batter_runs),2) AS Boundary_perc

FROM v_ball
GROUP BY batter
HAVING runs>2000
ORDER BY Boundary_perc DESC
LIMIT 10;

""")

            batter  runs  Boundary_perc
0  Abhishek Sharma  2241           0.18
1      RA Tripathi  2291           0.17
2          RR Pant  3742           0.16
3       MA Agarwal  2756           0.15
4         V Sehwag  2728           0.15
5        Q de Kock  3441           0.12
6   AB de Villiers  5162           0.08
7     AC Gilchrist  2069           0.00
8       AD Russell  2651           0.00
9         AJ Finch  2091           0.00

In [20]:
q("""
-- find an ideal middle_order  batter who can lift the run rate in overs 7 to 15.

SELECT batter,sum(is_legal) AS balls,sum(batter_runs) AS runs,
      ROUND(100.0* SUM(batter_runs)/SUM(is_legal),2) AS run_rate

FROM v_ball
WHERE phase = 'Middle'
GROUP BY batter
HAVING balls > 500

ORDER BY run_rate DESC
LIMIT 20;

""")

             batter  balls  runs  run_rate
0          V Sehwag    611  1062    173.81
1        RM Patidar    566   970    171.38
2          N Pooran    848  1351    159.32
3         H Klaasen    697  1099    157.68
4          CH Gayle   1285  2011    156.50
5        AD Russell    767  1182    154.11
6         SR Watson   1302  2006    154.07
7        GJ Maxwell   1163  1780    153.05
8          SE Marsh    971  1448    149.12
9          DR Smith    675  1004    148.74
10  B Sai Sudharsan    694  1031    148.56
11       JC Buttler   1303  1890    145.05
12         SA Yadav   1845  2664    144.39
13     Shubman Gill   1300  1864    143.38
14       RD Gaikwad    780  1093    140.13
15       MA Agarwal    781  1094    140.08
16          VR Iyer    524   731    139.50
17      YBK Jaiswal    582   811    139.35
18     Ishan Kishan   1091  1518    139.14
19         KL Rahul   1740  2412    138.62

In [21]:
q("""

-- Find a finisher:highest strike rate in the last five overs.

SELECT batter,SUM(batter_runs) AS runs,SUM(is_legal) AS balls,
      ROUND(100.0*SUM(batter_runs)/SUM(is_legal),2)  AS strike_rate

    FROM v_ball
    WHERE phase="Death"
    GROUP BY batter
    HAVING balls>500
    ORDER BY strike_rate DESC
    LIMIT 10;

    """)

           batter  runs  balls  strike_rate
0  AB de Villiers  1868    829       225.33
1         RR Pant  1035    513       201.75
2      AD Russell  1432    724       197.79
3         V Kohli  1525    807       188.97
4      MP Stoinis   962    521       184.64
5       RG Sharma  1527    837       182.44
6        KL Rahul   907    502       180.68
7        MS Dhoni  3468   1965       176.49
8        DJ Bravo   909    516       176.16
9      KD Karthik  1904   1091       174.52

In [22]:
q("""
-- find a powerplay opener who attacks from ball one.

SELECT batter,SUM(batter_runs) AS runs,SUM(is_legal) AS balls,
      ROUND(100.0*SUM(batter_runs)/SUM(is_legal),2)  AS strike_rate
   FROM v_ball
      WHERE phase="Powerplay"
      GROUP BY batter
      HAVING balls>500
      ORDER BY strike_rate DESC
      LIMIT 10;    """)

            batter  runs  balls  strike_rate
0  Abhishek Sharma  1287    744       172.98
1        SP Narine  1174    688       170.64
2      YBK Jaiswal  1579    984       160.47
3   P Simran Singh  1070    687       155.75
4      JM Bairstow   944    623       151.52
5          PP Shaw  1347    917       146.89
6         V Sehwag  1593   1096       145.35
7          CA Lynn   779    537       145.07
8       JC Buttler  1789   1257       142.32
9      RA Tripathi  1013    721       140.50

In [23]:
q("""
--Who is the mostt reliable in a chase-strike rate batting second?

SELECT batter,SUM(batter_runs) AS runs,SUM(is_legal) AS balls,
      ROUND(100.0*SUM(batter_runs)/SUM(is_legal),2)  AS strike_rate

      FROM v_ball
      WHERE "innings"=2
      GROUP BY batter
      HAVING balls>500
      ORDER BY strike_rate DESC
      LIMIT 10;  
""")

            batter  runs  balls  strike_rate
0        SP Narine   869    507       171.40
1       AD Russell  1130    660       171.21
2  Abhishek Sharma  1108    648       170.99
3         N Pooran  1218    729       167.08
4         V Sehwag  1427    869       164.21
5       GJ Maxwell  1164    734       158.58
6   P Simran Singh   832    527       157.87
7       JC Buttler  2289   1461       156.67
8      YBK Jaiswal  1351    875       154.40
9         SA Yadav  2131   1382       154.20

In [24]:
q("""
--which batters are hardest to bowl a dot ball to in the death overs?
SELECT batter,sum(is_legal) AS balls,
         SUM(case when batter_runs=0 AND is_legal=1
         then 1
         ELSE 0
         END ) AS dot_balls,
         ROUND (100.0*SUM(case WHEN 
         batter_runs=0 AND is_legal =1 
         THEN 1 ELSE 0
         END)/SUM(is_legal),2)AS
         dot_pct

FROM v_ball
WHERE phase='Death'
GROUP BY batter
HAVING balls >=500
ORDER BY dot_pct ASC
LIMIT 5;
""")

           batter  balls  dot_balls  dot_pct
0       JP Duminy    516        104    20.16
1  AB de Villiers    829        175    21.11
2        SK Raina    521        111    21.31
3        KL Rahul    502        110    21.91
4         V Kohli    807        185    22.92

In [25]:


q("""
--how do runs and wickets differ across the three phases of an innings?

select phase,sum(is_legal)as balls,sum(total_runs),
round(6.0*sum(total_runs)/sum(is_legal),2)as runs_per_over,
round(100.0*sum(is_wicket)/sum(is_legal),2)as wicket_perc

from v_ball
group by phase;

""")

       phase   balls  sum(total_runs)  runs_per_over  wicket_perc
0      Death   62205           104056          10.04         8.46
1     Middle  128191           169160           7.92         4.34
2  Powerplay   86921           116397           8.03         4.01

In [26]:
q(""" 
--which over of the innings is the most expensive?
SELECT over_number,
ROUND(6.0*SUM(total_runs)/SUM(is_legal),2) AS runs_per_over
FROM v_ball
GROUP BY OVER_NUMBER
ORDER BY runs_per_over DESC;

""")

    over_number  runs_per_over
0            19          11.39
1            18          10.53
2            17          10.12
3            16           9.46
4            15           9.05
5            14           8.74
6             5           8.68
7             4           8.65
8             3           8.63
9            13           8.43
10            2           8.37
11           12           8.17
12           11           8.13
13           10           7.96
14            8           7.77
15            9           7.66
16            1           7.60
17            7           7.47
18            6           6.98
19            0           6.28

In [27]:
q(""" 
--What is the average score at the end of the powerplay?

SELECT ROUND(AVG(pp_runs), 2) AS avg_powerplay_Score

FROM (SELECT match_id,innings, SUM(total_runs) AS pp_runs
FROM v_ball

WHERE phase='Powerplay' AND innings IN(1,2)
 GROUP BY match_id, innings);
 """)

   avg_powerplay_Score
0                48.14

In [28]:
q("""
SELECT bowler,SUM(bowler_wicket) AS wicket 
FROM v_ball
GROUP BY bowler
ORDER BY wicket DESC;
""")

               bowler  wicket
0           YS Chahal     228
1             B Kumar     215
2           SP Narine     199
3           PP Chawla     192
4            R Ashwin     187
..                ...     ...
563       Tilak Varma       0
564       VS Yeligati       0
565    Vivrant Sharma       0
566  Y Gnaneswara Rao       0
567       YBK Jaiswal       0

[568 rows x 2 columns]

In [29]:
q("""
SELECT bowler, SUM
(is_legal) AS balls,
ROUND(6.0*SUM(bowler_runs)/SUM(is_legal),2) AS b_economy
FROM v_ball
GROUP BY bowler
HAVING balls >500
ORDER BY b_economy
LIMIT 10;
""")

            bowler  balls  b_economy
0         A Kumble    965       6.58
1   M Muralitharan   1524       6.68
2       DL Vettori    777       6.79
3        SP Narine   4507       6.79
4         DW Steyn   2176       6.92
5          J Botha    694       6.92
6         R Sharma    928       7.02
7  Harbhajan Singh   3416       7.08
8       SL Malinga   2827       7.14
9      Rashid Khan   3387       7.16

In [30]:
q("""

--Which bowler takes a wicket most often - best strike rate in balls per wicket? 
--bowler, total ball, total wicket, balls per wicket

SELECT bowler,SUM(is_legal) AS total_balls,SUM(bowler_wicket) AS total_wicket,

    ROUND(1.0*SUM(is_legal)/SUM(bowler_wicket),2) As balls_per_wicket

FROM v_ball
GROUP BY bowler
having total_wicket>50
ORDER BY balls_per_wicket;

""")

          bowler  total_balls  total_wicket  balls_per_wicket
0     AD Russell         1806           123             14.68
1   JR Hazlewood         1008            65             15.51
2       K Rabada         2112           133             15.88
3       MA Starc         1083            68             15.93
4    Imran Tahir         1316            82             16.05
..           ...          ...           ...               ...
73      I Sharma         2419            96             25.20
74     IK Pathan         2043            80             25.54
75      AR Patel         3483           136             25.61
76     JH Kallis         1742            65             26.80
77       P Kumar         2524            90             28.04

[78 rows x 4 columns]

In [31]:
q("""
SELECT
    bowler,
    SUM(is_legal) AS balls,
    SUM(CASE WHEN batter_runs IN (4, 6) THEN 1 ELSE 0 END) AS boundaries,
    ROUND(
        100.0 * SUM(CASE WHEN batter_runs IN (4, 6) THEN 1 ELSE 0 END)
        / SUM(is_legal),
        2
    ) AS boundary_perc
FROM v_ball
GROUP BY bowler
HAVING SUM(is_legal) >= 1000
ORDER BY boundary_perc ASC
LIMIT 10;
""")

            bowler  balls  boundaries  boundary_perc
0   M Muralitharan   1524         170          11.15
1         R Bhatia   1636         188          11.49
2        SP Narine   4507         526          11.67
3         R Ashwin   4710         555          11.78
4         M Kartik   1149         138          12.01
5         SK Warne   1194         147          12.31
6         A Mishra   3371         423          12.55
7          PP Ojha   1899         243          12.80
8      Rashid Khan   3387         436          12.87
9  Harbhajan Singh   3416         441          12.91

In [32]:
q("""
--Which bowler bowls the most dot balls?
--bowler,balls,dot_ball,dot_perc

SELECT bowler,sum(is_legal) AS balls,SUM(case WHEN total_runs=0 AND is_legal=1
      THEN 1
      ELSE 0
      END)AS dot_balls,
    ROUND(100.0*SUM(CASE WHEN total_runs=0 AND is_legal=1
    THEN 1
    ELSE 0
    END)/SUM(is_legal),2) AS dot_perc

FROM v_ball
GROUP BY bowler
HAVING balls >=1000
ORDER BY dot_perc DESC
LIMIT 10;
""")

         bowler  balls  dot_balls  dot_perc
0      DW Steyn   2176       1019     46.83
1     JC Archer   1440        627     43.54
2      MM Patel   1355        590     43.54
3      M Morkel   1629        708     43.46
4    MG Johnson   1232        533     43.26
5  JR Hazlewood   1008        434     43.06
6       P Kumar   2524       1075     42.59
7     DL Chahar   1954        827     42.32
8      RP Singh   1775        744     41.92
9       A Nehra   1908        798     41.82

In [33]:
q("""
--How do bowlers actually take their wickets?

SELECT wicket_kind, COUNT(*) AS n

FROM v_ball
WHERE is_wicket=1

GROUP BY wicket_kind

ORDER BY n DESc;""")

             wicket_kind     n
0                 caught  9045
1                 bowled  2398
2                run out  1167
3                    lbw   871
4      caught and bowled   399
5                stumped   382
6           retired hurt    19
7             hit wicket    18
8            retired out     6
9  obstructing the field     4

In [34]:
q("""
SELECT CASE WHEN bowler_type LIKE                       -- spin or pace 
       '%Legbreak%' OR bowler_type LIKE 
       '%Offbreak%' OR bowler_type LIKE 
       '%Orthodox%' OR bowler_type LIKE 
       '%Wrist spin%' OR bowler_type LIKE 
       '%Googly%' THEN 'Spin' ELSE 'Pace' 
       END AS style,                                    -- branches of th 
       SUM(is_legal) AS balls,                          -- sample size 
       ROUND(6.0*SUM(bowler_runs)/SUM(is_legal),2)      -- runs per over 
              AS economy, 
       ROUND(100.0*SUM(bowler_wicket)/SUM(is_legal),2)  -- bowler's wicke 
              AS wicket_pct 
FROM   v_ball                                           -- one row = one 
WHERE  bowler_type IS NOT NULL AND                      -- drop the blanks 
       TRIM(bowler_type) <> '' 
GROUP  BY style;                                        -- one row per gr

""")

  style   balls  economy  wicket_pct
0  Pace  176859     8.57        4.93
1  Spin  100129     7.76        4.37

In [35]:
q("""
SELECT CASE WHEN bowler_type LIKE 'Left%'               -- spin or pace 
       THEN 'Left arm' ELSE 'Right arm' END             -- branches of th 
       AS arm, 
       batsman_type, 
       ROUND(6.0*SUM(bowler_runs)/SUM(is_legal),2)      -- runs per over 
              AS economy, 
       ROUND(100.0*SUM(bowler_wicket)/SUM(is_legal),2)  -- bowler's wicke 
              AS wicket_pct 
FROM   v_ball                                           -- one row = one 
WHERE  TRIM(COALESCE(bowler_type,'')) <> ''             -- drop the blanks 
       AND batsman_type IS NOT NULL                     -- and this too 
GROUP  BY arm, batsman_type;""")

         arm    batsman_type  economy  wicket_pct
0   Left arm   Left hand Bat     8.81        5.13
1   Left arm  Right hand Bat     8.49        4.97
2  Right arm   Left hand Bat     8.33        4.46
3  Right arm  Right hand Bat     8.16        4.78

In [36]:
q(""" 
SELECT bowler, SUM(bowler_wicket) AS wicket,
       ROUND(100.0 * SUM(bowler_wicket) / SUM(is_legal), 2) AS wicket_perc

FROM v_ball
WHERE bowler_type LIKE '%Legbreak%' OR
      bowler_type LIKE '%Offbreak%' OR
      bowler_type LIKE '%Orthodox%' OR
      bowler_type LIKE '%Wrist spin%' OR
      bowler_type LIKE '%Googly%'
GROUP BY bowler
ORDER BY wicket DESC
LIMIT 10;
""")

            bowler  wicket  wicket_perc
0        YS Chahal     228         5.79
1        SP Narine     199         4.42
2        PP Chawla     192         4.99
3         R Ashwin     187         3.97
4        RA Jadeja     177         4.23
5         A Mishra     174         5.16
6      Rashid Khan     168         4.96
7  Harbhajan Singh     150         4.39
8         AR Patel     136         3.90
9    Kuldeep Yadav     109         4.90

In [37]:
q("""
-- We need a death-overs bowler who is cheapest in overs 16 to 20

SELECT
    bowler,
    SUM(is_legal) AS balls,
    SUM(bowler_runs) AS bowler_runs,
    ROUND(
        6.0 * SUM(bowler_runs) / SUM(is_legal),
        2
    ) AS economy
FROM v_ball
WHERE over_number BETWEEN 16 AND 20
  AND is_legal = 1
GROUP BY bowler
HAVING balls > 300
ORDER BY economy ASC
LIMIT 10;
""")

        bowler  balls  bowler_runs  economy
0   SL Malinga    917         1132     7.41
1    SP Narine    763          989     7.78
2    JJ Bumrah   1237         1652     8.01
3  M Pathirana    314          427     8.16
4    CH Morris    586          806     8.25
5  Rashid Khan    360          500     8.33
6     DW Steyn    532          744     8.39
7      A Nehra    419          593     8.49
8       Z Khan    535          769     8.62
9     R Ashwin    337          486     8.65

In [38]:
q("""

SELECT
    bowler,
    SUM(is_legal) AS total_balls,
    SUM(bowler_wicket) AS wicket,
    ROUND(
            100.0 * SUM(bowler_wicket) / SUM(is_legal),
            2
        ) AS wicket_perc
FROM v_ball
WHERE phase='Powerplay'
GROUP BY bowler
    HAVING total_balls>300
    ORDER BY wicket DESC;""")

            bowler  total_balls  wicket  wicket_perc
0          B Kumar         2453      89         3.63
1         TA Boult         1644      72         4.38
2        DL Chahar         1527      67         4.39
3   Sandeep Sharma         1728      64         3.70
4         UT Yadav         1446      58         4.01
..             ...          ...     ...          ...
75    DE Bollinger          324      11         3.40
76    Mukesh Kumar          354      11         3.11
77       SM Curran          570      11         1.93
78    M Theekshana          312      10         3.21
79       JO Holder          354       9         2.54

[80 rows x 4 columns]

In [39]:

q("""
SELECT
    bowler,
    SUM(is_legal) AS balls,
    SUM(is_legal AND total_runs = 0) AS dot_balls,
    ROUND(100.0 * SUM(is_legal AND total_runs = 0) / SUM(is_legal), 2) AS dot_perc
FROM v_ball
WHERE phase = 'Death'
GROUP BY bowler
HAVING balls >= 300
ORDER BY dot_perc DESC
LIMIT 10;
""")

              bowler  balls  dot_balls  dot_perc
0          SP Narine   1075        397     36.93
1           CV Varun    310        112     36.13
2         MG Johnson    302        108     35.76
3        Rashid Khan    594        208     35.02
4           DW Steyn    634        218     34.38
5          PP Chawla    444        150     33.78
6           K Rabada    660        222     33.64
7  M Prasidh Krishna    542        182     33.58
8           A Mishra    521        167     32.05
9           MA Starc    333        106     31.83

In [40]:
q("""
SELECT
    COUNT(*) AS decisive_matches,

    SUM(
        CASE
            WHEN toss_winner = match_winner THEN 1
            ELSE 0
        END
    ) AS toss_winner_won,

    ROUND(
        100.0 * SUM(
            CASE
                WHEN toss_winner = match_winner THEN 1
                ELSE 0
            END
        ) / COUNT(*),
        2
    ) AS pct

FROM matches_clean
WHERE result = 'win';
""")

   decisive_matches  toss_winner_won    pct
0              1187              613  51.64

In [41]:
q("""
SELECT
    LOWER(toss_decision) AS decision,
    COUNT(*) AS total_tosses,
    ROUND(100.0 * COUNT(*) / (SELECT COUNT(*) FROM matches_clean), 2) AS pct
FROM matches_clean
GROUP BY LOWER(toss_decision);
""")

  decision  total_tosses    pct
0      bat           412  33.99
1    field           800  66.01

In [42]:
q("""
SELECT
    toss_winner,
    COUNT(*) AS toss_won
FROM matches_clean
GROUP BY toss_winner
ORDER BY toss_won DESC;
""")

                    toss_winner  toss_won
0                Mumbai Indians       156
1                Delhi Capitals       145
2           Sunrisers Hyderabad       139
3              Rajasthan Royals       134
4   Royal Challengers Bangalore       132
5         Kolkata Knight Riders       132
6           Chennai Super Kings       130
7                  Punjab Kings       126
8                Gujarat Titans        33
9          Lucknow Super Giants        29
10                Pune Warriors        20
11                Gujarat Lions        15
12       Rising Pune Supergiant        13
13         Kochi Tuskers Kerala         8

In [43]:
q(""" 
SELECT
    ROUND(AVG(first_innings_runs), 2) AS avg_first_innings_score
FROM v_match_totals;
""")

   avg_first_innings_score
0                   168.19

In [44]:
q("""
SELECT
    innings,
    ROUND(6.0 * SUM(total_runs) / SUM(is_legal), 2) AS run_rate
FROM v_ball
WHERE innings IN (1, 2)
GROUP BY innings
ORDER BY innings;""")

   innings  run_rate
0        1      8.49
1        2      8.37

In [45]:
q("""
SELECT
    CASE innings
        WHEN 1 THEN 'Batting first'
        WHEN 2 THEN 'Batting second'
    END AS batting_order,
    ROUND(AVG(wickets), 2) AS average_wickets_lost
FROM v_innings
GROUP BY innings
ORDER BY average_wickets_lost DESC;
""")

    batting_order  average_wickets_lost
0   Batting first                  6.13
1  Batting second                  5.70

In [46]:
q("""
SELECT
    COUNT(*) AS match_with_200plus,
    SUM(chase_won) AS successfully_chased
FROM v_match_totals
WHERE first_innings_runs >= 200;
""")

   match_with_200plus  successfully_chased
0                 198                   46

In [47]:
q("""
SELECT
    MAX(CASE WHEN chase_won = 0 THEN first_innings_runs END) AS biggest_defend,
    MAX(CASE WHEN chase_won = 1 THEN first_innings_runs END) AS biggest_chased
FROM v_match_totals;
""")

   biggest_defend  biggest_chased
0             287             264

In [48]:
q("""
-- Which ground has hosted the most matches?
-- Table: matches_clean; column: venue_clean

SELECT
    venue_clean AS ground,
    COUNT(*) AS matches_hosted
FROM matches_clean
WHERE venue_clean IS NOT NULL
  AND TRIM(venue_clean) <> ''
GROUP BY venue_clean
ORDER BY matches_hosted DESC
LIMIT 10;
""")

                                ground  matches_hosted
0                     Wankhede Stadium             130
1                         Eden Gardens             104
2               MA Chidambaram Stadium              95
3                M Chinnaswamy Stadium              89
4   Rajiv Gandhi International Stadium              87
5               Sawai Mansingh Stadium              66
6                     Feroz Shah Kotla              60
7  Dubai International Cricket Stadium              46
8                 Arun Jaitley Stadium              41
9                Narendra Modi Stadium              37

In [49]:
q(""" SELECT
m.venue_clean,
COUNT(DISTINCT m.match_id) AS matches, ROUND(avg(i.runs),1) AS avg_score
FROM matches_clean m
JOIN v_innings i ON i.match_id=m.match_id
GROUP BY m.venue_clean
HAVING matches>=25
ORDER BY avg_score DESC
LIMIT 10;
""")

                                         venue_clean  matches  avg_score
0                               Arun Jaitley Stadium       41      180.0
1                              Narendra Modi Stadium       37      177.8
2                                  Brabourne Stadium       27      172.3
3       Punjab Cricket Association IS Bindra Stadium       26      170.7
4  Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...       26      167.6
5                                   Wankhede Stadium      130      166.9
6                              M Chinnaswamy Stadium       89      164.8
7                             Sawai Mansingh Stadium       66      161.1
8                 Rajiv Gandhi International Stadium       87      161.1
9                                       Eden Gardens      104      160.9

In [50]:
q(""" 
--which team has won the most matches? 

SELECT match_winner,COUNT (*) AS wins 
FROM matches_clean
WHERE result='win'
GROUP BY match_winner
ORDER BY wins DESC;
""")

                   match_winner  wins
0                Mumbai Indians   153
1           Chennai Super Kings   145
2   Royal Challengers Bangalore   138
3         Kolkata Knight Riders   136
4           Sunrisers Hyderabad   128
5                  Punjab Kings   125
6                Delhi Capitals   122
7              Rajasthan Royals   120
8                Gujarat Titans    42
9          Lucknow Super Giants    32
10       Rising Pune Supergiant    15
11                Gujarat Lions    13
12                Pune Warriors    12
13         Kochi Tuskers Kerala     6

In [51]:
q(""" 
-- which team scores fastest in the powerplay? 
--v_ball table 
--batting_team,run_rate having sum (is_legal)>=3000

SELECT batting_team,
      ROUND(6.0*SUM(total_runs)/sum(is_legal),2) AS run_rate
FROM v_ball
WHERE phase='Powerplay'
GROUP BY batting_team
HAVING SUM(is_legal)>=3000
ORDER BY run_rate DESC
LIMIT 10; """)

                  batting_team  run_rate
0                 Punjab Kings      8.21
1          Sunrisers Hyderabad      8.20
2             Rajasthan Royals      8.07
3               Delhi Capitals      8.03
4        Kolkata Knight Riders      8.02
5               Mumbai Indians      7.93
6  Royal Challengers Bangalore      7.91
7          Chennai Super Kings      7.85

In [52]:
q(""" 
--which team relies most on boundaries for its run?
--run rate 100* batter_runs/legal_ball 4 6 only having sum(is_legal)>=10000
SELECT
    batting_team AS team,
    SUM(CASE WHEN batter_runs IN (4, 6) THEN batter_runs ELSE 0 END) AS boundary_runs,
    SUM(total_runs) AS total_runs,
    ROUND(
        100.0 * SUM(CASE WHEN batter_runs IN (4, 6) THEN batter_runs ELSE 0 END)
        / SUM(batter_runs), 2
    ) AS boundary_percentage
FROM v_ball
GROUP BY batting_team
HAVING SUM(is_legal) >=10000
ORDER BY boundary_percentage DESC
LIMIT 10;
""")

                          team  boundary_runs  total_runs  boundary_percentage
0               Mumbai Indians          27486       46517                62.30
1        Kolkata Knight Riders          24846       42540                61.84
2                 Punjab Kings          25986       44352                61.67
3  Royal Challengers Bangalore          26220       44890                61.44
4             Rajasthan Royals          22718       39159                60.90
5               Delhi Capitals          24688       43297                59.97
6          Chennai Super Kings          24186       42557                59.80
7          Sunrisers Hyderabad          24982       44948                58.50

In [53]:
q("""  
--which player has won the most player-of-the-match awards? 
--player,award_count 
--matches_clean.player_of_match
SELECT
    player_of_match,
    COUNT(*) AS awards
FROM matches_clean
GROUP BY player_of_match
ORDER BY awards DESC
LIMIT 10;
""")

  player_of_match  awards
0  AB de Villiers      25
1        CH Gayle      22
2       RG Sharma      21
3         V Kohli      20
4        MS Dhoni      18
5       DA Warner      18
6       SP Narine      17
7       RA Jadeja      17
8        KL Rahul      17
9       YK Pathan      16

In [54]:
q(""" 
--How does thw way batters get out change across the phases? 
--phases,wiket_kind=caught,bowled,run out,n
--v_ball table is_wicket 
SELECT
    phase,
    wicket_kind,
    COUNT(*) AS N,
    ROUND(
        100.0 * COUNT(*) /
        SUM(COUNT(*)) OVER (PARTITION BY phase),
        2
    ) AS percentage
FROM v_ball
WHERE is_wicket = 1
  AND wicket_kind IN ('caught', 'bowled', 'run out')
GROUP BY phase, wicket_kind
ORDER BY phase,N DESC;
""")

       phase wicket_kind     N  percentage
0      Death      caught  3289       68.52
1      Death      bowled   877       18.27
2      Death     run out   634       13.21
3     Middle      caught  3484       73.55
4     Middle      bowled   909       19.19
5     Middle     run out   344        7.26
6  Powerplay      caught  2272       73.93
7  Powerplay      bowled   612       19.92
8  Powerplay     run out   189        6.15

In [55]:
q(""" 
--which batter is most often run out? 
--player_name,run_out_count 
--player_out,wicket_kind='run out'
SELECT
    player_out AS player_name,
    COUNT(*) AS run_out_count
FROM v_ball
WHERE wicket_kind = 'run out'
GROUP BY player_out
ORDER BY run_out_count DESC
LIMIT 10;


""")

       player_name  run_out_count
0         S Dhawan             16
1        G Gambhir             16
2         SK Raina             15
3       KD Karthik             15
4        AT Rayudu             15
5   AB de Villiers             14
6          M Vijay             12
7     F du Plessis             12
8        YK Pathan             11
9  Y Venugopal Rao             11

In [56]:
q(""" 
--how many matches wereplayed each season? 
--matches_clean
--season_year 
SELECT season_year,COUNT (*) AS matches
FROM matches_clean
GROUP BY season_year;
""")

    season_year  matches
0          2008       58
1          2009       57
2          2010       60
3          2011       73
4          2012       74
5          2013       76
6          2014       60
7          2015       59
8          2016       60
9          2017       59
10         2018       60
11         2019       60
12         2020       60
13         2021       60
14         2022       74
15         2023       74
16         2024       71
17         2025       74
18         2026       43

In [57]:
q("""
SELECT
    bowler,
    COUNT(*) AS times_dismissed
FROM v_ball
WHERE batter = 'V Kohli'
 AND bowler_wicket = 1
GROUP BY bowler
ORDER BY times_dismissed DESC;
""")

             bowler  times_dismissed
0    Sandeep Sharma                7
1           A Nehra                6
2    Mohammed Shami                5
3         JJ Bumrah                5
4         SP Narine                4
..              ...              ...
127      AD Mathews                1
128       AC Thomas                1
129       A Symonds                1
130        A Nortje                1
131        A Kamboj                1

[132 rows x 2 columns]

In [58]:
q(""" 
--which bowler dismissed a named batter most often ? 
--v_kohil
--v_ball
SELECT
    bowler,batter,
    COUNT(*) AS times_out
FROM v_ball
WHERE bowler_wicket=1
GROUP BY bowler,batter
ORDER BY times_out DESC;
""")

               bowler           batter  times_out
0           SP Narine        RG Sharma          8
1            A Mishra        RG Sharma          7
2             B Kumar        AM Rahane          7
3           JJ Bumrah          RR Pant          7
4           MM Sharma        AT Rayudu          7
...               ...              ...        ...
10305  Zeeshan Ansari  B Sai Sudharsan          1
10306  Zeeshan Ansari     F du Plessis          1
10307  Zeeshan Ansari  J Fraser-McGurk          1
10308  Zeeshan Ansari         KL Rahul          1
10309  Zeeshan Ansari         WG Jacks          1

[10310 rows x 3 columns]

In [59]:
q("""
SELECT 
    batter,
    SUM(is_legal) AS balls,
    SUM(batter_runs) AS runs,
    ROUND(
        100.0 * SUM(batter_runs) / SUM(is_legal),
        2
    ) AS sr
FROM v_ball
WHERE phase = 'Powerplay' 
  AND is_wicket = 0
GROUP BY batter
HAVING balls >= 500
ORDER BY sr DESC;
""")

             batter  balls  runs      sr
0         SP Narine    640  1174  183.44
1   Abhishek Sharma    712  1287  180.76
2       YBK Jaiswal    948  1579  166.56
3    P Simran Singh    658  1070  162.61
4       JM Bairstow    601   944  157.07
5           PP Shaw    866  1347  155.54
6          V Sehwag   1036  1593  153.76
7           CA Lynn    520   779  149.81
8       RA Tripathi    685  1013  147.88
9        JC Buttler   1216  1788  147.04
10         SA Yadav    685   984  143.65
11        DA Warner   2312  3316  143.43
12     AC Gilchrist    978  1384  141.51
13  B Sai Sudharsan    597   844  141.37
14     Ishan Kishan   1015  1432  141.08
15     F du Plessis   1617  2281  141.06
16         CH Gayle   1689  2373  140.50
17          WP Saha    990  1389  140.30
18         SK Raina   1117  1552  138.94
19     Shubman Gill   1378  1912  138.75
20       D Padikkal    704   964  136.93
21        Q de Kock   1445  1963  135.85
22      BB McCullum   1155  1555  134.63
23          M Vohra    514   689  134.05
24        RG Sharma   1874  2479  132.28
25          V Kohli   2527  3339  132.13
26        SV Samson   1149  1518  132.11
27       RD Gaikwad    984  1298  131.91
28         KL Rahul   1777  2336  131.46
29       RV Uthappa   1566  2035  129.95
30       MA Agarwal   1092  1409  129.03
31         DR Smith    943  1213  128.63
32         PA Patel   1485  1903  128.15
33         S Dhawan   2674  3415  127.71
34        AM Rahane   2078  2647  127.38
35        G Gambhir   1795  2275  126.74
36           N Rana    632   799  126.42
37   AB de Villiers    584   722  123.63
38    Mandeep Singh    519   633  121.97
39         AJ Finch    747   909  121.69
40     SR Tendulkar    951  1143  120.19
41          M Vijay   1323  1572  118.82
42        MK Pandey    954  1124  117.82
43          SS Iyer    840   987  117.50
44        SR Watson   1213  1415  116.65
45         R Dravid    811   905  111.59
46       MEK Hussey    747   828  110.84
47        JH Kallis    938  1036  110.45
48        AT Rayudu    705   777  110.21
49         SE Marsh    709   767  108.18

In [60]:
q(""" 

SELECT b.batter AS players,
     SUM(b.batter_runs) AS runs,
     (SELECT SUM(X.bowler_wicket) FROM v_ball AS x
     WHERE x.bowler=b.batter)AS wickets

    FROM v_ball b
    GROUP BY b.batter
HAVING runs>=1000 AND wickets>=50
    ORDER BY runs DESC
    LIMIT 10;""")

      players  runs  wickets
0   SR Watson  3874       92
1  KA Pollard  3412       69
2   RA Jadeja  3412      177
3   HH Pandya  2877       82
4  AD Russell  2651      123
5   JH Kallis  2427       65
6    AR Patel  1947      136
7   SP Narine  1820      199
8   KH Pandya  1796      102
9    DJ Bravo  1560      183

In [61]:
q("""
select batter,
sum(is_legal) as balls,
round(100.0*sum(batter_runs)/sum(is_legal),2) as sr
from v_ball
where innings=2 and phase='Death'
group by batter
having balls>=200
order by sr desc
limit 10;
""")

           batter  balls      sr
0  AB de Villiers    295  209.83
1         SS Iyer    215  187.44
2       DA Miller    439  186.33
3         RR Pant    214  185.51
4       SV Samson    207  183.57
5      KA Pollard    429  183.45
6      SO Hetmyer    217  180.65
7         V Kohli    336  180.65
8      AD Russell    265  174.72
9       YK Pathan    331  174.32