In [4]:
import sqlite3
import pandas as pd
con=sqlite3.connect('C:\\Users\\yasee\\OneDrive\\Desktop\\Sem 3 projects\\project 3.1\\data\\raw\\ipl.db')

def q(sql):
    return pd.read_sql(sql,con)

In [5]:
def run_sql_file(path):
    with open(path,'r') as f:
        script=f.read()
        con.executescript(script)
        con.commit()
        print('ran',path)

In [6]:
run_sql_file("C:\\Users\\yasee\\OneDrive\\Desktop\\Sem 3 projects\\project 3.1\\sql\\test.sql")

ran C:\Users\yasee\OneDrive\Desktop\Sem 3 projects\project 3.1\sql\test.sql

In [7]:
run_sql_file("C:\\Users\\yasee\\OneDrive\\Desktop\\Sem 3 projects\\project 3.1\\sql\\practice\\01_nulls_and_blanks.sql")

ran C:\Users\yasee\OneDrive\Desktop\Sem 3 projects\project 3.1\sql\practice\01_nulls_and_blanks.sql

In [8]:
q("""SELECT COUNT(*) AS blank_before
FROM players
WHERE TRIM(field_pos) = '';""")

   blank_before
0           612

In [9]:
q("""SELECT COUNT(*) AS null_after
  FROM v_players_clean
  WHERE field_pos_clean IS NULL;""")

   null_after
0         700

In [10]:
run_sql_file(r"C:\\Users\\yasee\\OneDrive\\Desktop\\Sem 3 projects\\project 3.1\\sql\\practice\\02_merge_categories.sql")

ran C:\\Users\\yasee\\OneDrive\\Desktop\\Sem 3 projects\\project 3.1\\sql\\practice\\02_merge_categories.sql

In [11]:
q("""SELECT DISTINCT team_name 
FROM teams
ORDER BY team_name;""")

                      team_name
0           Chennai Super Kings
1               Deccan Chargers
2                Delhi Capitals
3                 Gujarat Lions
4                Gujarat Titans
5          Kochi Tuskers Kerala
6         Kolkata Knight Riders
7          Lucknow Super Giants
8                Mumbai Indians
9                 Pune Warriors
10                 Punjab Kings
11             Rajasthan Royals
12       Rising Pune Supergiant
13      Rising Pune Supergiants
14  Royal Challengers Bangalore
15          Sunrisers Hyderabad

In [12]:
run_sql_file(r'C:\Users\yasee\OneDrive\Desktop\Sem 3 projects\project 3.1\sql\practice\03_venue_names.sql')

ran C:\Users\yasee\OneDrive\Desktop\Sem 3 projects\project 3.1\sql\practice\03_venue_names.sql

In [13]:
q("""SELECT venue,count(*) as matches
FROM matches
WHERE venue IN('Wankhede Stadium','Wankhede Stadium, Mumbai')
GROUP BY venue;""")

                      venue  matches
0          Wankhede Stadium       73
1  Wankhede Stadium, Mumbai       57

In [14]:
q("""SELECT venue, COUNT(*) AS matches
FROM matches
GROUP BY venue
ORDER BY matches DESC LIMIT 5;""")

                      venue  matches
0              Eden Gardens       77
1          Wankhede Stadium       73
2     M Chinnaswamy Stadium       65
3          Feroz Shah Kotla       60
4  Wankhede Stadium, Mumbai       57

In [15]:
q("""SELECT venue_clean,COUNT(*) AS matches 
FROM v_matches_venue
GROUP BY venue_clean
ORDER BY matches DESC LIMIT 5;""")

                          venue_clean  matches
0                    Wankhede Stadium      130
1                        Eden Gardens      104
2              MA Chidambaram Stadium       95
3               M Chinnaswamy Stadium       89
4  Rajiv Gandhi International Stadium       87

In [16]:
q("""SELECT COUNT(*) AS rows, COUNT (DISTINCT venue) AS names
FROM venues;""")

   rows  names
0    63     59

In [17]:
q("""SELECT count(*),venue,city
FROM venues
GROUP BY venue
ORDER BY COUNT(*) DESC
LIMIT 10;""")

   count(*)                                              venue       city
0         2                            Sharjah Cricket Stadium        NaN
1         2  Maharaja Yadavindra Singh International Cricke...     Mohali
2         2                Dubai International Cricket Stadium        NaN
3         2                 Dr DY Patil Sports Academy, Mumbai     Mumbai
4         1                   Zayed Cricket Stadium, Abu Dhabi  Abu Dhabi
5         1                           Wankhede Stadium, Mumbai     Mumbai
6         1                                   Wankhede Stadium     Mumbai
7         1       Vidarbha Cricket Association Stadium, Jamtha     Nagpur
8         1                                    SuperSport Park  Centurion
9         1                         Subrata Roy Sahara Stadium       Pune

In [18]:
run_sql_file(r'C:\Users\yasee\OneDrive\Desktop\Sem 3 projects\project 3.1\sql\practice\04_dedope_venues.sql')

ran C:\Users\yasee\OneDrive\Desktop\Sem 3 projects\project 3.1\sql\practice\04_dedope_venues.sql

In [19]:
q("""SELECT COUNT(*),venue,city
FROM v_venues_clean
GROUP BY venue
ORDER BY COUNT(*) DESC
LIMIT 10;""")

   COUNT(*)                                             venue            city
0         1                  Zayed Cricket Stadium, Abu Dhabi       Abu Dhabi
1         1                          Wankhede Stadium, Mumbai          Mumbai
2         1                                  Wankhede Stadium          Mumbai
3         1      Vidarbha Cricket Association Stadium, Jamtha          Nagpur
4         1                                   SuperSport Park       Centurion
5         1                        Subrata Roy Sahara Stadium            Pune
6         1                                  St George's Park  Port Elizabeth
7         1                              Sheikh Zayed Stadium       Abu Dhabi
8         1                           Sharjah Cricket Stadium         Sharjah
9         1  Shaheed Veer Narayan Singh International Stadium          Raipur

In [20]:
run_sql_file(r"C:\Users\yasee\OneDrive\Desktop\Sem 3 projects\project 3.1\sql\practice\05_city_fallback.sql")

ran C:\Users\yasee\OneDrive\Desktop\Sem 3 projects\project 3.1\sql\practice\05_city_fallback.sql

In [21]:
q("""SELECT  city_clean from v_city_clean where city_clean is null;""")

Empty DataFrame
Columns: [city_clean]
Index: []

In [22]:
q("""SELECT venue,
count(*) AS no_city 
FROm matches
WHERE city IS NULL
GROUP BY venue""")

                                 venue  no_city
0  Dubai International Cricket Stadium       33
1              Sharjah Cricket Stadium       18

In [23]:
run_sql_file(r'C:\Users\yasee\OneDrive\Desktop\Sem 3 projects\project 3.1\sql\practice\06_season_year.sql')

ran C:\Users\yasee\OneDrive\Desktop\Sem 3 projects\project 3.1\sql\practice\06_season_year.sql

In [24]:
q("""SELECT season,
       COUNT(*) AS matches 
FROM matches 
WHERE season = '2020/21'
GROUP BY season;""")

    season  matches
0  2020/21       60

In [25]:
q("""SELECT DISTINCT season,season_year FROM v_season WHERE season ='2020/21';""")

    season  season_year
0  2020/21         2020

In [26]:
run_sql_file(r'C:\Users\yasee\OneDrive\Desktop\Sem 3 projects\project 3.1\sql\practice\07_win_definition.sql')

ran C:\Users\yasee\OneDrive\Desktop\Sem 3 projects\project 3.1\sql\practice\07_win_definition.sql

In [27]:
q("""SELECT * FROM matches_clean;""")

,match_id,venue_clean,city_clean,season_year,result,match_winner,player_of_match,toss_decision
0,335982,M Chinnaswamy Stadium,Bangalore,2008,win,Kolkata Knight Riders,BB McCullum,field
1,1082591,Rajiv Gandhi International Stadium,Hyderabad,2017,win,Sunrisers Hyderabad,Yuvraj Singh,field
2,1082592,Maharashtra Cricket Association Stadium,Pune,2017,win,Rising Pune Supergiant,SPD Smith,field
3,1082593,Saurashtra Cricket Association Stadium,Rajkot,2017,win,Kolkata Knight Riders,CA Lynn,field
4,1082594,Holkar Cricket Stadium,Indore,2017,win,Punjab Kings,GJ Maxwell,field
...,...,...,...,...,...,...,...,...
1207,1529282,Arun Jaitley Stadium,Delhi,2026,win,Royal Challengers Bangalore,JR Hazlewood,field
1208,1529283,Maharaja Yadavindra Singh International Cricke...,New Chandigarh,2026,win,Rajasthan Royals,D Ferreira,field
1209,1529284,Wankhede Stadium,Mumbai,2026,win,Sunrisers Hyderabad,H Klaasen,bat
1210,1529285,Narendra Modi Stadium,Ahmedabad,2026,win,Gujarat Titans,JO Holder,field
1211,1529286,Sawai Mansingh Stadium,Jaipur,2026,win,Delhi Capitals,KL Rahul,bat

In [28]:
run_sql_file(r'c:\Users\yasee\OneDrive\Desktop\Sem 3 projects\project 3.1\sql\practice\08_matches_clean.sql')

ran c:\Users\yasee\OneDrive\Desktop\Sem 3 projects\project 3.1\sql\practice\08_matches_clean.sql

In [29]:
import ast
import pandas as pd
d = pd.read_sql('SELECT * FROM deliveries WHERE fielders_involved IS NOT NULL ', con )
d['fielders']=d['fielders_involved'].apply(ast.literal_eval)

d=d.explode('fielders')
d['fielders'].value_counts().head(5)

fielders
MS Dhoni          258
KD Karthik        228
RV Uthappa        169
AB de Villiers    148
V Kohli           142
Name: count, dtype: int64

In [30]:
q("""SELECT result,COUNt(*) AS n
FROM matches 
GROUP BY result;""")

      result     n
0  no result     9
1        tie    16
2        win  1187